### PR TITLE
plist -o and -i can be either a file or a directory

### PR DESCRIPTION
**Pull request by garriguv**
Allows specifying the name of the outputted plist

### CODE REVIEW

**Comment by michaelengland** [comment]
Can you update the CLI usage docs to reflect that? Also, check that it may be useful to do a similar thing with all the other generators too (and usage).

**Comment by michaelengland** [comment]
Can you rebase again? Then travis should pick up the less borked version.

**Comment by michaelengland** [comment]
Cheers. I think it's a good plan :+1:

**Comment by garriguv** [comment]
:rocket: :shipit:

**Comment by michaelengland** [comment]
:+1: GJ

**Pull request merged**
